name: Release

on:
  push:
    branches: 
      - 'feature/**'
      - 'issue/**'
      - dev

jobs:
  # This workflow contains a single job called "release"
  release-dev:
    name: Build & Deploy to Cloud run
    environment: totoexperiments
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with: 
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.CICD_SERVICE_ACCOUNT }}

    - name: Create Environment Variables
      run: |
        export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
        export PACKAGE_NAME=$(cat package.json | grep name | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build --build-arg SUPERMARKET_API_ENDPOINT=${{ secrets.SUPERMARKET_API_ENDPOINT }} --build-arg AUTH_API_ENDPOINT=${{ secrets.AUTH_API_ENDPOINT }} --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} . -t eu.gcr.io/${{ secrets.GCP_PID }}/${{env.PACKAGE_NAME}}:${{env.PACKAGE_VERSION}}
 
    - name: Push Docker image to Dockerhub 
      run: |
        docker push eu.gcr.io/${{ secrets.GCP_PID }}/${{env.PACKAGE_NAME}}:${{env.PACKAGE_VERSION}}
    
    - name: Setup GCloud 
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PID }}
        service_account_key: ${{ secrets.CICD_SERVICE_ACCOUNT }}
        export_default_credentials: true
    
    - name: Deploy image
      run: | 
        gcloud run deploy ${{env.PACKAGE_NAME}} --project=${{ secrets.GCP_PID }} --service-account=${{ secrets.SERVICE_ACCOUNT }} --image=eu.gcr.io/${{ secrets.GCP_PID }}/${{env.PACKAGE_NAME}}:${{env.PACKAGE_VERSION}} --platform=managed --region=europe-west1 --allow-unauthenticated